export const Root = {
    color_default: '#ffffff',
    color_button: '#6a5acd',
    color_button_secondary: "#e6e6fa",
    color_link: '#6a5acd',
    blue: '#007bff',
    indigo: '#6610f2',
    purple: '#6f42c1',
    pink: '#e83e8c',
    red: '#dc3545',
    orange: '#fd7e14',
    yellow: '#ffc107',
    green: '#28a745',
    teal: '#20c997',
    cyan: '#17a2b8',
    white: '#fff',
    gray: '#6c757d',
    grayDark: '#343a40',
    primary: '#007bff',
    secondary: '#6c757d',
    success: '#28a745',
    info: '#17a2b8',
    warning: '#ffc107',
    danger: '#dc3545',
    light: '#f8f9fa',
    dark: '#343a40',
    boxShadow: "rgba(0, 0, 0, 0.35) 0px 5px 15px",
    border: '1px solid #6a5acd',
    breakpointXS: '0',
    breakpointSM: '576px',
    breakpointMD: '768px',
    breakpointLG: '992px',
    breakpointXL: '1200px',
    fontFamilySansSerif:
      '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans","Liberation Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"',
    fontFamilyMonospace:
      'SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace',
  };
  