export const commentsData = [
  {
    id: 1,
    avatar: 'URL_AVATAR_1',
    name: 'Usuário1',
    time: '10:30 AM',
    text: 'Este é um ótimo comentário! @Usuário2 concorda? #Discussão',
    likes: 5,
  },
  {
    id: 2,
    avatar: 'URL_AVATAR_2',
    name: 'Usuário2',
    time: '11:45 AM',
    text: 'Estou gostando dessa discussão. @Usuário3, o que você acha? #Opiniões',
    likes: 8,
  },
  {
    id: 3,
    avatar: 'URL_AVATAR_3',
    name: 'Usuário3',
    time: '12:15 PM',
    text: 'Que interessante! Adorei. @Usuário4, suas ideias são incríveis! #Inovação',
    likes: 12,
  },
  {
    id: 4,
    avatar: 'URL_AVATAR_4',
    name: 'Usuário4',
    time: '2:00 PM',
    text: 'Isso me fez pensar... @Usuário5, você já considerou isso antes? #Reflexão',
    likes: 3,
  },
  {
    id: 5,
    avatar: 'URL_AVATAR_5',
    name: 'Usuário5',
    time: '3:30 PM',
    text: 'Belo comentário! @Usuário6, você tem alguma experiência com isso? #Feedback',
    likes: 7,
  },
  {
    id: 6,
    avatar: 'URL_AVATAR_6',
    name: 'Usuário6',
    time: '4:45 PM',
    text: 'Estou aprendendo muito com isso. @Usuário7, você já pensou nisso dessa forma? #Aprendizado',
    likes: 10,
  },
  {
    id: 7,
    avatar: 'URL_AVATAR_7',
    name: 'Usuário7',
    time: '5:20 PM',
    text: 'Nunca pensei nisso dessa forma. @Usuário8, compartilhe sua opinião! #Inovação',
    likes: 15,
  },
  {
    id: 8,
    avatar: 'URL_AVATAR_8',
    name: 'Usuário8',
    time: '6:10 PM',
    text: 'Excelente ponto! @Usuário9, o que você acha disso? #Discussão',
    likes: 6,
  },
  {
    id: 9,
    avatar: 'URL_AVATAR_9',
    name: 'Usuário9',
    time: '8:00 PM',
    text: 'Gostaria de saber mais sobre isso. @Usuário10, você pode compartilhar mais detalhes? #Curiosidade',
    likes: 4,
  },
  {
    id: 10,
    avatar: 'URL_AVATAR_10',
    name: 'Usuário10',
    time: '9:30 PM',
    text: 'Esse tópico é fascinante. @Usuário1, suas opiniões são sempre valiosas! #Interessante',
    likes: 9,
  },
];

export default commentsData;
