
export const tasks = [
    {
        name: 'Project Inception: Define Scope and Objectives',
        action: 'defineScope && setObjectives',
        assigner: 'Michael Johnson',
        avatar: '',
        missingTime: '10',
        dateStarted: '01/02/2023',
        dateDelivery: '15/02/2023',
        stateTask: 'verify',
        status: 'archived',
    },
    {
        name: 'Code Refactoring: Improve Codebase Efficiency',
        action: 'refactorCode && optimizePerformance',
        assigner: 'Sophie Davis',
        avatar: '',
        missingTime: '12',
        dateStarted: '05/02/2023',
        dateDelivery: '18/02/2023',
        stateTask: 'inProgress',
        status: 'archived',
    },
    {
        name: 'Content Strategy: Plan and Create Blog Calendar',
        action: 'planContent && writePosts',
        assigner: 'Daniel White',
        avatar: '',
        missingTime: '8',
        dateStarted: '10/02/2023',
        dateDelivery: '18/02/2023',
        stateTask: 'pending',
        status: 'archived',
    },
    {
        name: 'User Feedback Gathering: Conduct Surveys and Interviews',
        action: 'createSurveys && conductInterviews',
        assigner: 'Olivia Garcia',
        avatar: '',
        missingTime: '15',
        dateStarted: '15/02/2023',
        dateDelivery: '28/02/2023',
        stateTask: 'verify',
        status: 'archived',
    },
    {
        name: 'Database Optimization: Enhance Database Performance',
        action: 'optimizeDatabase && monitorMetrics',
        assigner: 'Liam Smith',
        avatar: '',
        missingTime: '14',
        dateStarted: '20/02/2023',
        dateDelivery: '06/03/2023',
        stateTask: 'inProgress',
        status: 'active',
    },
    {
        name: 'Social Media Campaign: Launch Product Promotion',
        action: 'createCampaign && monitorEngagement',
        assigner: 'Ava Wilson',
        avatar: '',
        missingTime: '20',
        dateStarted: '25/02/2023',
        dateDelivery: '12/03/2023',
        stateTask: 'pending',
        status: 'active',
    },
    {
        name: 'Code Review Marathon: Ensure Code Quality',
        action: 'conductReviews && addressFeedback',
        assigner: 'Noah Taylor',
        avatar: '',
        missingTime: '18',
        dateStarted: '01/03/2023',
        dateDelivery: '15/03/2023',
        stateTask: 'verify',
        status: 'completed',
    },
    {
        name: 'Training Sessions: Conduct Team Skill Workshops',
        action: 'planTraining && facilitateSessions',
        assigner: 'Mia Anderson',
        avatar: '',
        missingTime: '12',
        dateStarted: '06/03/2023',
        dateDelivery: '18/03/2023',
        stateTask: 'inProgress',
        status: 'completed',
    },
    {
        name: 'Budget Analysis: Evaluate Financial Performance',
        action: 'analyzeBudget && reportFindings',
        assigner: 'Lucas Martin',
        avatar: '',
        missingTime: '10',
        dateStarted: '10/03/2023',
        dateDelivery: '18/03/2023',
        stateTask: 'pending',
        status: 'completed',
    },
    {
        name: 'Event Planning: Coordinate Team Building Activity',
        action: 'organizeEvent && manageLogistics',
        assigner: 'Isabella Perez',
        avatar: '',
        missingTime: '15',
        dateStarted: '15/03/2023',
        dateDelivery: '28/03/2023',
        stateTask: 'verify',
        status: 'completed',
    },
    {
        name: 'Security Audit: Review and Enhance System Security',
        action: 'conductAudit && implementSecurityMeasures',
        assigner: 'Jackson Hernandez',
        avatar: '',
        missingTime: '14',
        dateStarted: '20/03/2023',
        dateDelivery: '05/04/2023',
        stateTask: 'inProgress',
        status: 'completed',
    },
    {
        name: 'UI/UX Redesign: Improve User Interface and Experience',
        action: 'redesignUI && enhanceUX',
        assigner: 'Sophia Turner',
        avatar: '',
        missingTime: '18',
        dateStarted: '25/03/2023',
        dateDelivery: '10/04/2023',
        stateTask: 'pending',
        status: 'completed',
    },
    {
        name: 'Documentation Sprint: Update Project Documentation',
        action: 'reviewDocs && makeUpdates',
        assigner: 'Henry Davis',
        avatar: '',
        missingTime: '20',
        dateStarted: '01/04/2023',
        dateDelivery: '15/04/2023',
        stateTask: 'verify',
        status: 'completed',
    },
    {
        name: 'Strategic Planning: Develop Long-Term Business Strategy',
        action: 'strategize && setGoals',
        assigner: 'Ella Smith',
        avatar: '',
        missingTime: '12',
        dateStarted: '06/04/2023',
        dateDelivery: '18/04/2023',
        stateTask: 'inProgress',
        status: 'active',
    },
    {
        name: 'Marketing Analytics: Analyze Campaign Effectiveness',
        action: 'analyzeData && provideInsights',
        assigner: 'Gabriel Martin',
        avatar: '',
        missingTime: '10',
        dateStarted: '10/04/2023',
        dateDelivery: '18/04/2023',
        stateTask: 'pending',
        status: 'active',
    },
    {
        name: 'Team Collaboration: Foster Cross-Functional Communication',
        action: 'facilitateMeetings && encourageTeamBuilding',
        assigner: 'Aiden Brown',
        avatar: '',
        missingTime: '15',
        dateStarted: '15/04/2023',
        dateDelivery: '28/04/2023',
        stateTask: 'verify',
        status: 'active',
    },
    {
        name: 'Product Launch: Plan and Execute New Product Launch',
        action: 'planLaunch && coordinateExecution',
        assigner: 'Emma Taylor',
        avatar: '',
        missingTime: '14',
        dateStarted: '20/04/2023',
        dateDelivery: '05/05/2023',
        stateTask: 'inProgress',
        status: 'active',
    },

    {
        name: 'Market Research: Study Industry Trends and Competitors',
        action: 'conductResearch && analyzeCompetition',
        assigner: 'Sophie Garcia',
        avatar: '',
        missingTime: '20',
        dateStarted: '01/05/2023',
        dateDelivery: '15/05/2023',
        stateTask: 'verify',
        status: 'active',
    },
    {
        name: 'Quality Assurance: Implement QA Best Practices',
        action: 'establishQA && conductAudits',
        assigner: 'Jackson Wilson',
        avatar: '',
        missingTime: '12',
        dateStarted: '06/05/2023',
        dateDelivery: '18/05/2023',
        stateTask: 'inProgress',
        status: 'active',
    },
    {
        name: 'Customer Feedback: Gather and Analyze Customer Input',
        action: 'collectFeedback && analyzeSentiment',
        assigner: 'Mia Anderson',
        avatar: '',
        missingTime: '10',
        dateStarted: '10/05/2023',
        dateDelivery: '18/05/2023',
        stateTask: 'pending',
        status: 'active',
    },
    {
        name: 'Employee Training: Roll Out Skill Development Program',
        action: 'planTraining && conductWorkshops',
        assigner: 'Noah Smith',
        avatar: '',
        missingTime: '15',
        dateStarted: '15/05/2023',
        dateDelivery: '28/05/2023',
        stateTask: 'verify',
        status: 'active',
    },
    {
        name: 'Financial Reporting: Prepare Quarterly Financial Reports',
        action: 'compileReports && presentFindings',
        assigner: 'Isabella Brown',
        avatar: '',
        missingTime: '14',
        dateStarted: '20/05/2023',
        dateDelivery: '05/06/2023',
        stateTask: 'inProgress',
        status: 'active',
    },
    {
        name: 'Community Engagement: Initiate CSR Activities',
        action: 'planActivities && engageCommunity',
        assigner: 'Liam Martinez',
        avatar: '',
        missingTime: '18',
        dateStarted: '25/05/2023',
        dateDelivery: '10/06/2023',
        stateTask: 'pending',
        status: 'active',
    },
    {
        name: 'Legal Compliance: Ensure Adherence to Regulatory Standards',
        action: 'conductAudit && implementComplianceMeasures',
        assigner: 'Emma Johnson',
        avatar: '',
        missingTime: '20',
        dateStarted: '01/06/2023',
        dateDelivery: '15/06/2023',
        stateTask: 'verify',
        status: 'active',
    },
    {
        name: 'Tech Upgrade: Implement Latest Technological Solutions',
        action: 'upgradeSystems && testCompatibility',
        assigner: 'Gabriel Wilson',
        avatar: '',
        missingTime: '12',
        dateStarted: '06/06/2023',
        dateDelivery: '18/06/2023',
        stateTask: 'inProgress',
        status: 'active',
    },
    {
        name: 'Employee Wellness Program: Promote Work-Life Balance',
        action: 'implementWellnessInitiatives && gatherFeedback',
        assigner: 'Sophia Davis',
        avatar: '',
        missingTime: '10',
        dateStarted: '10/06/2023',
        dateDelivery: '18/06/2023',
        stateTask: 'pending',
        status: 'active',
    },
    {
        name: 'Product Maintenance: Regular Software Updates',
        action: 'releaseUpdates && monitorPerformance',
        assigner: 'Henry Turner',
        avatar: '',
        missingTime: '15',
        dateStarted: '15/06/2023',
        dateDelivery: '28/06/2023',
        stateTask: 'verify',
        status: 'archived',
    },
    {
        name: 'Diversity and Inclusion: Implement Inclusive Practices',
        action: 'promoteDiversity && fosterInclusion',
        assigner: 'Ella Garcia',
        avatar: '',
        missingTime: '14',
        dateStarted: '20/06/2023',
        dateDelivery: '05/07/2023',
        stateTask: 'inProgress',
        status: 'archived',
    },
    {
        name: 'Market Expansion: Explore New Geographical Markets',
        action: 'researchMarkets && planExpansion',
        assigner: 'Aiden Smith',
        avatar: '',
        missingTime: '18',
        dateStarted: '25/06/2023',
        dateDelivery: '10/07/2023',
        stateTask: 'pending',
        status: 'archived',
    },
    {
        name: 'Brand Refresh: Update Company Branding',
        action: 'refreshBranding && communicateChanges',
        assigner: 'Emma Turner',
        avatar: '',
        missingTime: '20',
        dateStarted: '01/07/2023',
        dateDelivery: '15/07/2023',
        stateTask: 'verify',
        status: 'close',
    },
    {
        name: 'Employee Engagement: Conduct Team Building Activities',
        action: 'organizeEvents && strengthenTeamBonding',
        assigner: 'Liam Brown',
        avatar: '',
        missingTime: '12',
        dateStarted: '06/07/2023',
        dateDelivery: '18/07/2023',
        stateTask: 'inProgress',
        status: 'close',
    },
    {
        name: 'Cybersecurity Measures: Enhance Data Protection',
        action: 'upgradeSecurity && conductTraining',
        assigner: 'Sophie Garcia',
        avatar: '',
        missingTime: '10',
        dateStarted: '10/07/2023',
        dateDelivery: '18/07/2023',
        stateTask: 'pending',
        status: 'close',
    },
    {
        name: 'Innovation Forum: Foster Creativity and Idea Generation',
        action: 'hostForum && facilitateBrainstorming',
        assigner: 'Aiden Smith',
        avatar: '',
        missingTime: '15',
        dateStarted: '15/07/2023',
        dateDelivery: '28/07/2023',
        stateTask: 'verify',
        status: 'archived',
    },
    {
        name: 'Financial Forecast: Predict Future Financial Trends',
        action: 'analyzeData && makePredictions',
        assigner: 'Emma Wilson',
        avatar: '',
        missingTime: '14',
        dateStarted: '20/07/2023',
        dateDelivery: '05/08/2023',
        stateTask: 'inProgress',
        status: 'archived',
    }
]