export const tasks = [
    {
        name: 'Mobile Marvel: Crafting a Cutting-Edge Cell Phone Design',
        action: 'design && marked',
        assigner: 'Temotio Luis',
        avatar: '',
        missingTime: '10',
        dateStarted: '10/11/2023',
        dateDelivery: '20/11/2023',
        stateTask: 'verify',
    },
    {
        name: 'Web Wonders: Developing an Interactive Website Interface',
        action: 'develop && test',
        assigner: 'Alexandra Johnson',
        avatar: '',
        missingTime: '15',
        dateStarted: '12/11/2023',
        dateDelivery: '27/11/2023',
        stateTask: 'inProgress',
    },
    {
        name: 'Data Dynamo: Analyzing Big Data Trends for Insights',
        action: 'analyze && report',
        assigner: 'Carlos Rodriguez',
        avatar: '',
        missingTime: '8',
        dateStarted: '15/11/2023',
        dateDelivery: '23/11/2023',
        stateTask: 'pending',
    },
    {
        name: 'Social Spark: Creating Engaging Social Media Content',
        action: 'createContent && schedulePosts',
        assigner: 'Emily Thompson',
        avatar: '',
        missingTime: '12',
        dateStarted: '18/11/2023',
        dateDelivery: '30/11/2023',
        stateTask: 'verify',
    },
    {
        name: 'Code Crunch: Optimizing Algorithm Efficiency',
        action: 'optimize && testPerformance',
        assigner: 'Daniel White',
        avatar: '',
        missingTime: '14',
        dateStarted: '20/11/2023',
        dateDelivery: '04/12/2023',
        stateTask: 'inProgress',
    },
    {
        name: 'UI/UX Unicorn: Enhancing User Interface and Experience',
        action: 'improveUI && enhanceUX',
        assigner: 'Sophia Martin',
        avatar: '',
        missingTime: '10',
        dateStarted: '22/11/2023',
        dateDelivery: '02/12/2023',
        stateTask: 'pending',
    },
    {
        name: 'Content Creation Crusade: Developing Blog Posts and Articles',
        action: 'writePosts && editContent',
        assigner: 'Gabriel Perez',
        avatar: '',
        missingTime: '18',
        dateStarted: '25/11/2023',
        dateDelivery: '10/12/2023',
        stateTask: 'verify',
    },
    // {
    //     name: 'Security Sentinel: Conducting System Security Audit',
    //     action: 'audit && implementSecurityMeasures',
    //     assigner: 'Olivia Garcia',
    //     avatar: '',
    //     missingTime: '12',
    //     dateStarted: '28/11/2023',
    //     dateDelivery: '10/12/2023',
    //     stateTask: 'inProgress',
    // },
    // {
    //     name: 'Marketing Maven: Developing a Comprehensive Marketing Plan',
    //     action: 'plan && executeCampaigns',
    //     assigner: 'Lucas Smith',
    //     avatar: '',
    //     missingTime: '20',
    //     dateStarted: '01/12/2023',
    //     dateDelivery: '15/12/2023',
    //     stateTask: 'pending',
    // },
    // {
    //     name: 'Event Extravaganza: Organizing a Memorable Company Event',
    //     action: 'organize && coordinateLogistics',
    //     assigner: 'Ava Wilson',
    //     avatar: '',
    //     missingTime: '15',
    //     dateStarted: '04/12/2023',
    //     dateDelivery: '20/12/2023',
    //     stateTask: 'verify',
    // },
    // {
    //     name: 'Quality Quest: Conducting Rigorous Quality Assurance Testing',
    //     action: 'performTests && documentBugs',
    //     assigner: 'Isabella Brown',
    //     avatar: '',
    //     missingTime: '14',
    //     dateStarted: '07/12/2023',
    //     dateDelivery: '21/12/2023',
    //     stateTask: 'inProgress',
    // },
    // {
    //     name: 'Tech Trek: Staying Updated on the Latest Technological Trends',
    //     action: 'research && summarizeFindings',
    //     assigner: 'Liam Davis',
    //     avatar: '',
    //     missingTime: '10',
    //     dateStarted: '10/12/2023',
    //     dateDelivery: '20/12/2023',
    //     stateTask: 'pending',
    // },
    // {
    //     name: 'Finance Fiesta: Budgeting and Financial Analysis',
    //     action: 'createBudget && analyzeFinancialData',
    //     assigner: 'Ella Martinez',
    //     avatar: '',
    //     missingTime: '18',
    //     dateStarted: '13/12/2023',
    //     dateDelivery: '28/12/2023',
    //     stateTask: 'verify',
    // },
    // {
    //     name: 'Creative Crusader: Ideation and Brainstorming Sessions',
    //     action: 'brainstormIdeas && presentConcepts',
    //     assigner: 'Noah Taylor',
    //     avatar: '',
    //     missingTime: '12',
    //     dateStarted: '16/12/2023',
    //     dateDelivery: '30/12/2023',
    //     stateTask: 'inProgress',
    // },
    // {
    //     name: 'Learning Lane: Organizing Training Programs for Team Members',
    //     action: 'planTraining && conductSessions',
    //     assigner: 'Mia Anderson',
    //     avatar: '',
    //     missingTime: '15',
    //     dateStarted: '19/12/2023',
    //     dateDelivery: '03/01/2024',
    //     stateTask: 'pending',
    // },
    // {
    //     name: 'Health and Wellness: Promoting Employee Well-being Initiatives',
    //     action: 'implementWellnessProgram && gatherFeedback',
    //     assigner: 'Jackson Clark',
    //     avatar: '',
    //     missingTime: '20',
    //     dateStarted: '22/12/2023',
    //     dateDelivery: '10/01/2024',
    //     stateTask: 'verify',
    // },
    // {
    //     name: 'Localization Legend: Adapting Software for Global Markets',
    //     action: 'localizeContent && conductUserFeedback',
    //     assigner: 'Sophie Turner',
    //     avatar: '',
    //     missingTime: '14',
    //     dateStarted: '25/12/2023',
    //     dateDelivery: '08/01/2024',
    //     stateTask: 'inProgress',
    // },
    // {
    //     name: 'Accessibility Advocate: Ensuring Inclusive Design Practices',
    //     action: 'auditAccessibility && implementImprovements',
    //     assigner: 'Henry Hernandez',
    //     avatar: '',
    //     missingTime: '10',
    //     dateStarted: '28/12/2023',
    //     dateDelivery: '12/01/2024',
    //     stateTask: 'pending',
    // },
];
